[package]
name = "uda"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/brian-armstrong/uda"
description = "SDR blocks/pipeline library"
license = "MIT"

[dependencies]
yagi = "0.0.3"
